apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  selector:
    matchLabels:
      app: vets-service
  replicas: 1
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
      - name: vets-service
        image: kpnreg.azurecr.io/spring-petclinic-vets-service:version
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "mysql,cloud"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-root-password
          - name: CONFIG_SERVER_URL
            value: "http://config-server:80/"
        # readinessProbe:
        #   initialDelaySeconds: 15
        #   httpGet:
        #     path: /
        #     port: 8080
        # livenessProbe:
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   httpGet:
        #     path: /
        #     port: 8080
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
      imagePullSecrets:
      - name: acr-registry
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
spec:
  type: ClusterIP
  selector:
    app: vets-service
  ports:
  - name: http
    port: 80
    targetPort: 8080