apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  selector:
    matchLabels:
      app: discovery-server
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: kpnreg.azurecr.io/spring-petclinic-discovery-server:version
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_SERVER_URL
          value: "http://config-server:80/"
        # readinessProbe:
        #   initialDelaySeconds: 60
        #   preiodSeconds: 10
        #   failureThreshold: 3
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        # livenessProbe:
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        #   failureThreshold: 3
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
      imagePullSecrets:
      - name: acr-registry
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  type: ClusterIP
  selector:
    app: discovery-server
  ports:
  - name: http
    port: 80
    targetPort: 8080