apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: kpnreg.azurecr.io/spring-petclinic-config-server:version
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "cloud"
        # readinessProbe:
        #   initialDelaySeconds: 60
        #   preiodSeconds: 10
        #   failureThreshold: 3
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        # livenessProbe:
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        #   failureThreshold: 3
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
      imagePullSecrets:
      - name: acr-registry
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
  - name: http
    port: 80
    targetPort: 8080